# Exploratory Data Analysis (EDA) 

## setup, imports and ETL pipeline execution
before beginning the EDA i will import all the required libaries, load the raw dataset and run the automated ETL pipeline created in the ETL Notebook.

In [2]:
%pip install plotly

Collecting plotly
  Using cached plotly-6.9.0-py3-none-any.whl.metadata (9.0 kB)
Collecting narwhals>=1.15.1 (from plotly)
  Using cached narwhals-2.25.0-py3-none-any.whl.metadata (15 kB)
Requirement already satisfied: packaging in c:\users\ovrcm\appdata\roaming\python\python312\site-packages (from plotly) (26.2)
Using cached plotly-6.9.0-py3-none-any.whl (9.9 MB)
Using cached narwhals-2.25.0-py3-none-any.whl (467 kB)
Installing collected packages: narwhals, plotly
Successfully installed narwhals-2.25.0 plotly-6.9.0
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.3.1 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import plotly.graph_objects as go

## Load Raw Dataset

In [5]:
df_raw = pd.read_csv("../data/raw/DataCoSupplyChainDataset.csv", encoding='latin1')
df_raw.head()

,Type,Days for shipping (real),Days for shipment (scheduled),Benefit per order,Sales per customer,Delivery Status,Late_delivery_risk,Category Id,Category Name,Customer City,...,Order Zipcode,Product Card Id,Product Category Id,Product Description,Product Image,Product Name,Product Price,Product Status,shipping date (DateOrders),Shipping Mode
0,DEBIT,3,4,91.250000,314.640015,Advance shipping,0,73,Sporting Goods,Caguas,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,2/3/2018 22:56,Standard Class
1,TRANSFER,5,4,-249.089996,311.359985,Late delivery,1,73,Sporting Goods,Caguas,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/18/2018 12:27,Standard Class
2,CASH,4,4,-247.779999,309.720001,Shipping on time,0,73,Sporting Goods,San Jose,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/17/2018 12:06,Standard Class
3,DEBIT,3,4,22.860001,304.809998,Advance shipping,0,73,Sporting Goods,Los Angeles,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/16/2018 11:45,Standard Class
4,PAYMENT,2,4,134.210007,298.250000,Advance shipping,0,73,Sporting Goods,Caguas,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/15/2018 11:24,Standard Class

## Run the ETL pipeline

In [6]:
from src.etl_pipeline import etl_pipeline

df = etl_pipeline()
df.head()

,type,days_for_shipping_real,days_for_shipment_scheduled,benefit_per_order,sales_per_customer,delivery_status,late_delivery_risk,category_id,category_name,customer_city,...,product_price,product_status,shipping_date_dateorders,shipping_mode,shipping_delay,order_month,order_weekday,shipping_weekday,high_value_order,customer_full_name
0,DEBIT,3,4,91.250000,314.640015,Advance shipping,0,73,Sporting Goods,Caguas,...,327.75,0,2018-02-03 22:56:00,Standard Class,-1,1,Wednesday,Saturday,True,Cally Holloway
1,TRANSFER,5,4,-249.089996,311.359985,Late delivery,1,73,Sporting Goods,Caguas,...,327.75,0,2018-01-18 12:27:00,Standard Class,1,1,Saturday,Thursday,True,Irene Luna
2,CASH,4,4,-247.779999,309.720001,Shipping on time,0,73,Sporting Goods,San Jose,...,327.75,0,2018-01-17 12:06:00,Standard Class,0,1,Saturday,Wednesday,True,Gillian Maldonado
3,DEBIT,3,4,22.860001,304.809998,Advance shipping,0,73,Sporting Goods,Los Angeles,...,327.75,0,2018-01-16 11:45:00,Standard Class,-1,1,Saturday,Tuesday,True,Tana Tate
4,PAYMENT,2,4,134.210007,298.250000,Advance shipping,0,73,Sporting Goods,Caguas,...,327.75,0,2018-01-15 11:24:00,Standard Class,-2,1,Saturday,Monday,True,Orli Hendricks

# dataset overview

In [7]:
print("shape of cleaned dataset:", df.shape)

shape of cleaned dataset: (180519, 59)

# preview first 10 rows

In [8]:
display(df.head(10))

,type,days_for_shipping_real,days_for_shipment_scheduled,benefit_per_order,sales_per_customer,delivery_status,late_delivery_risk,category_id,category_name,customer_city,...,product_price,product_status,shipping_date_dateorders,shipping_mode,shipping_delay,order_month,order_weekday,shipping_weekday,high_value_order,customer_full_name
0,DEBIT,3,4,91.250000,314.640015,Advance shipping,0,73,Sporting Goods,Caguas,...,327.75,0,2018-02-03 22:56:00,Standard Class,-1,1,Wednesday,Saturday,True,Cally Holloway
1,TRANSFER,5,4,-249.089996,311.359985,Late delivery,1,73,Sporting Goods,Caguas,...,327.75,0,2018-01-18 12:27:00,Standard Class,1,1,Saturday,Thursday,True,Irene Luna
2,CASH,4,4,-247.779999,309.720001,Shipping on time,0,73,Sporting Goods,San Jose,...,327.75,0,2018-01-17 12:06:00,Standard Class,0,1,Saturday,Wednesday,True,Gillian Maldonado
3,DEBIT,3,4,22.860001,304.809998,Advance shipping,0,73,Sporting Goods,Los Angeles,...,327.75,0,2018-01-16 11:45:00,Standard Class,-1,1,Saturday,Tuesday,True,Tana Tate
4,PAYMENT,2,4,134.210007,298.250000,Advance shipping,0,73,Sporting Goods,Caguas,...,327.75,0,2018-01-15 11:24:00,Standard Class,-2,1,Saturday,Monday,True,Orli Hendricks
5,TRANSFER,6,4,18.580000,294.980011,Shipping canceled,0,73,Sporting Goods,Tonawanda,...,327.75,0,2018-01-19 11:03:00,Standard Class,2,1,Saturday,Friday,True,Kimberly Flowers
6,DEBIT,2,1,95.180000,288.420013,Late delivery,1,73,Sporting Goods,Caguas,...,327.75,0,2018-01-15 10:42:00,First Class,1,1,Saturday,Monday,True,Constance Terrell
7,TRANSFER,2,1,68.430000,285.140015,Late delivery,1,73,Sporting Goods,Miami,...,327.75,0,2018-01-15 10:21:00,First Class,1,1,Saturday,Monday,True,Erica Stevens
8,CASH,3,2,133.720001,278.589996,Late delivery,1,73,Sporting Goods,Caguas,...,327.75,0,2018-01-16 10:00:00,Second Class,1,1,Saturday,Tuesday,True,Nichole Olsen
9,CASH,2,1,132.149994,275.309998,Late delivery,1,73,Sporting Goods,San Ramon,...,327.75,0,2018-01-15 09:39:00,First Class,1,1,Saturday,Monday,True,Oprah Delacruz

# Data types

In [9]:
print("\nData types:")
display(df.dtypes)

Data types:

type                                      str
days_for_shipping_real                  int64
days_for_shipment_scheduled             int64
benefit_per_order                     float64
sales_per_customer                    float64
delivery_status                           str
late_delivery_risk                      int64
category_id                             int64
category_name                             str
customer_city                             str
customer_country                          str
customer_email                            str
customer_fname                            str
customer_id                             int64
customer_lname                            str
customer_password                         str
customer_segment                          str
customer_state                            str
customer_street                           str
customer_zipcode                      float64
department_id                           int64
department_name                           str
latitude                              float64
longitude                             float64
market                                    str
order_city                                str
order_country                             str
order_customer_id                       int64
order_date_dateorders          datetime64[us]
order_id                                int64
order_item_cardprod_id                  int64
order_item_discount                   float64
order_item_discount_rate              float64
order_item_id                           int64
order_item_product_price              float64
order_item_profit_ratio               float64
order_item_quantity                     int64
sales                                 float64
order_item_total                      float64
order_profit_per_order                float64
order_region                              str
order_state                               str
order_status                              str
order_zipcode                         float64
product_card_id                         int64
product_category_id                     int64
product_description                   float64
product_image                             str
product_name                              str
product_price                         float64
product_status                          int64
shipping_date_dateorders       datetime64[us]
shipping_mode                             str
shipping_delay                          int64
order_month                             int32
order_weekday                             str
shipping_weekday                          str
high_value_order                         bool
customer_full_name                        str
dtype: object

# Missing values

In [10]:
print("\nmissing values:")
display(df.isna().sum())

missing values:

type                                0
days_for_shipping_real              0
days_for_shipment_scheduled         0
benefit_per_order                   0
sales_per_customer                  0
delivery_status                     0
late_delivery_risk                  0
category_id                         0
category_name                       0
customer_city                       0
customer_country                    0
customer_email                      0
customer_fname                      0
customer_id                         0
customer_lname                      0
customer_password                   0
customer_segment                    0
customer_state                      0
customer_street                     0
customer_zipcode                    0
department_id                       0
department_name                     0
latitude                            0
longitude                           0
market                              0
order_city                          0
order_country                       0
order_customer_id                   0
order_date_dateorders               0
order_id                            0
order_item_cardprod_id              0
order_item_discount                 0
order_item_discount_rate            0
order_item_id                       0
order_item_product_price            0
order_item_profit_ratio             0
order_item_quantity                 0
sales                               0
order_item_total                    0
order_profit_per_order              0
order_region                        0
order_state                         0
order_status                        0
order_zipcode                  155679
product_card_id                     0
product_category_id                 0
product_description            180519
product_image                       0
product_name                        0
product_price                       0
product_status                      0
shipping_date_dateorders            0
shipping_mode                       0
shipping_delay                      0
order_month                         0
order_weekday                       0
shipping_weekday                    0
high_value_order                    0
customer_full_name                  0
dtype: int64

# Descriptive statistics

In [11]:
print("\ndescriptive statistics:")
display(df.describe())

descriptive statistics:

,days_for_shipping_real,days_for_shipment_scheduled,benefit_per_order,sales_per_customer,late_delivery_risk,category_id,customer_id,customer_zipcode,department_id,latitude,...,order_profit_per_order,order_zipcode,product_card_id,product_category_id,product_description,product_price,product_status,shipping_date_dateorders,shipping_delay,order_month
count,180519.000000,180519.000000,180519.000000,180519.000000,180519.000000,180519.000000,180519.000000,180519.000000,180519.000000,180519.000000,...,180519.000000,24840.000000,180519.000000,180519.000000,0.0,180519.000000,180519.0,180519,180519.000000,180519.000000
mean,3.497654,2.931847,21.974989,183.107609,0.548291,31.851451,6691.379495,35920.529950,5.443460,29.719955,...,21.974989,55426.132327,692.509764,31.851451,NaN,141.232550,0.0,2016-06-16 05:45:23.202433,0.565807,6.235449
min,0.000000,0.000000,-4274.979980,7.490000,0.000000,2.000000,1.000000,0.000000,2.000000,-33.937553,...,-4274.979980,1040.000000,19.000000,2.000000,NaN,9.990000,0.0,2015-01-03 00:00:00,-2.000000,1.000000
25%,2.000000,2.000000,7.000000,104.379997,0.000000,18.000000,3258.500000,725.000000,4.000000,18.265432,...,7.000000,23464.000000,403.000000,18.000000,NaN,50.000000,0.0,2015-09-25 06:59:00,0.000000,3.000000
50%,3.000000,4.000000,31.520000,163.990005,1.000000,29.000000,6457.000000,19380.000000,5.000000,33.144863,...,31.520000,59405.000000,627.000000,29.000000,NaN,59.990002,0.0,2016-06-15 08:32:00,1.000000,6.000000
75%,5.000000,4.000000,64.800003,247.399994,1.000000,45.000000,9779.000000,78207.000000,7.000000,39.279617,...,64.800003,90008.000000,1004.000000,45.000000,NaN,199.990005,0.0,2017-03-04 21:29:00,1.000000,9.000000
max,6.000000,4.000000,911.799988,1939.989990,1.000000,76.000000,20757.000000,99205.000000,12.000000,48.781933,...,911.799988,99301.000000,1363.000000,76.000000,NaN,1999.989990,0.0,2018-02-06 22:14:00,4.000000,12.000000
std,1.623722,1.374449,104.433526,120.043670,0.497664,15.640064,4162.918106,37542.434755,1.629246,9.813646,...,104.433526,31919.279101,336.446807,15.640064,NaN,139.732492,0.0,NaN,1.490966,3.403571

# duplicate rows

In [12]:
print("\nnumber of duplicated rows:", df.duplicated().sum())

number of duplicated rows: 0

### Reflection

The dataset overview confirms that the cleaned DataCo Supply Chain Dataset is structured correctly after running the automated ETL pipeline. The dataset contains a mix of numerical and categorical variables, and the descriptive statistics highlight variation in shipping times, order values, and customer information.

This step provides a solid foundation for the next stages of the EDA.